# Fit DAG

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
    
import sys
sys.path.append("..")
sys.path.append("../prediction_src")

import pandas as pd

import numpy as np


from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

import random
import pickle
import sklearn

from sklearn.metrics import roc_auc_score, brier_score_loss
from collections import defaultdict


from sklearn.model_selection import KFold, cross_validate 

from evaluate_prediction_model import *

from sklearn.base import BaseEstimator, ClassifierMixin
import statsmodels.api as sm

from prediction_src.fit_prediction_model import *

from prediction_src.prediction_pipeline import model_pipeline


from scipy import stats

In [3]:
is_sum = False
as_grouped = True
nvf=False

In [4]:
from params import *

In [5]:
filepath = "../data/processed/n80_df.pkl"

In [6]:
NO_DURCHFALL_COLS = GROUP_COLS.copy()
NO_DURCHFALL_MODEL_COLS = GROUP_MODEL_COLS.copy()

NO_DURCHFALL_COLS.pop(NO_DURCHFALL_COLS.index("Durchfall"))

NO_DURCHFALL_MODEL_COLS.pop(NO_DURCHFALL_MODEL_COLS.index("Durchfall"))

'Durchfall'

In [7]:
NO_DURCHFALL_DYSPAREUNIE_COLS = NO_DURCHFALL_COLS.copy()
NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS = NO_DURCHFALL_MODEL_COLS.copy()
NO_DURCHFALL_DYSPAREUNIE_COLS.pop(NO_DURCHFALL_DYSPAREUNIE_COLS.index("Dyspareunie"))

NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS.pop(NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS.index("Dyspareunie"))

'Dyspareunie'

In [8]:
NO_DURCHFALL_DYSCHEZIE_COLS = NO_DURCHFALL_COLS.copy()
NO_DURCHFALL_DYSCHEZIE_MODEL_COLS = NO_DURCHFALL_MODEL_COLS.copy()

NO_DURCHFALL_DYSCHEZIE_COLS.pop(NO_DURCHFALL_DYSCHEZIE_COLS.index("Urinieren"))

NO_DURCHFALL_DYSCHEZIE_MODEL_COLS.pop(NO_DURCHFALL_DYSCHEZIE_MODEL_COLS.index("Urinieren"))

'Urinieren'

In [9]:
N_FOLDS

5

In [10]:
# Alle DAG-Prädiktoren:
basis_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,GROUP_COLS,GROUP_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)
classifier
SMWrapperClassifier(family=<statsmodels.genmod.families.family.Binomial object at 0x7f21073f22f0>)
[0.61669667 0.63774704 0.62450602 0.643743   0.62234572]
[0.84106135 1.07078075 1.3281343  1.12775135 0.89182019]
[0.01791167 0.01342988 0.02439833 0.03926086 0.02296996]
dict_keys(['fit_time', 'score_time', 'estimator', 'test_score'])
Mean AUC during cross validation: 0.6290076904904291

In [11]:
basis_metrics_of_interest = calc_eval_metrics(basis_model_dict,MET_LIST)

In [12]:
basis_metrics_of_interest

,AUC,Brier Score Loss,Calibration Intercept,Calibration Slope
Model,,,,
endo_data_as_groupedTrue_is_sumFalse_nvfFalse,0.656,0.02,0.339,1.094

In [11]:
# Nur Menstruationsschmerz als Prädiktor:
menstruationsschmerz_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,MENS_COLS,MENS_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(

In [12]:
# Alle DAG-Prädiktoren OHNE Durchfall:
durchfall_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_COLS,NO_DURCHFALL_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(

In [13]:
# Alle DAG-Prädiktoren OHNE Durchfall OHNE Urinieren:
urinieren_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_DYSCHEZIE_COLS,NO_DURCHFALL_DYSCHEZIE_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(

In [14]:
# Alle DAG-Prädiktoren OHNE Durchfall OHNE Dyspareunie:
dyspareunie_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_DYSPAREUNIE_COLS,NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(

In [15]:
# Alle DAG-Prädiktoren mit zusätzlichen NVF-Variablen:
nvf_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,NVF_CODE_TO_LABEL,NVF_GROUP_COLS,NVF_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 400, in _score
    y_pred = method_caller(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
  File "/mnt/c/Users/Juliana/dev/llm_priors_for_bayesian_dt/.env/lib/python3.10/site-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: SMWrapperClassifier should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(

In [16]:
with open("../models/DAG_model_thresh_new.pkl","wb") as f:
    pickle.dump(basis_model_dict,f)

In [17]:
with open("../models/menstruationsschmerz_predictor.pkl","wb") as f:
    pickle.dump(menstruationsschmerz_dict,f)

In [18]:
with open("../models/DAG_model_durchfall.pkl","wb") as f:
    pickle.dump(durchfall_model_dict,f)

In [19]:
with open("../models/DAG_model_dyspareunie.pkl","wb") as f:
    pickle.dump(dyspareunie_model_dict,f)

In [20]:
with open("../models/DAG_model_urinieren.pkl","wb") as f:
    pickle.dump(urinieren_model_dict,f)

In [21]:
with open("../models/DAG_model_nvf.pkl","wb") as f:
    pickle.dump(nvf_model_dict,f)

## Load models

In [31]:
with open("../models/DAG_model_durchfall.pkl","rb") as f:
    durchfall_model_dict = pickle.load(f)

In [44]:
with open("../models/DAG_model_thresh_new.pkl","rb") as f:
    basis_model_dict = pickle.load(f)

In [35]:
with open("../models/DAG_model_dyspareunie.pkl","rb") as f:
    dyspareunie_model_dict = pickle.load(f)

In [36]:
with open("../models/DAG_model_urinieren.pkl","rb") as f:
    urinieren_model_dict = pickle.load(f)

In [41]:
with open("../models/menstruationsschmerz_predictor.pkl","rb") as f:
    menstruationsschmerz_dict = pickle.load(f)

In [23]:
nvf_model = nvf_model_dict[list(nvf_model_dict.keys())[0]]["model"]

In [45]:
basis_model = basis_model_dict[list(basis_model_dict.keys())[0]]["model"]

In [42]:
menstruationsschmerz_model = menstruationsschmerz_dict[list(menstruationsschmerz_dict.keys())[0]]["model"]

In [32]:
durchfall_dag_model = durchfall_model_dict[list(durchfall_model_dict.keys())[0]]["model"]

In [37]:
dyspareunie_dag_model = dyspareunie_model_dict[list(dyspareunie_model_dict.keys())[0]]["model"]

In [38]:
urinieren_dag_model = urinieren_model_dict[list(urinieren_model_dict.keys())[0]]["model"]

In [38]:
nvf_model.coef_table_.round(3) # endometriosis without adenomyosis

,feature,coef,odds_ratio,p_value,ci_lower,ci_upper
0,Intercept,-4.213,0.015,0.000,-4.287,-4.139
1,Menstruationsschmerzen,0.838,2.312,0.000,0.707,0.969
2,Bauchschmerzen,0.583,1.791,0.010,0.137,1.029
3,Kopfschmerzen,0.741,2.098,0.009,0.184,1.298
4,Verdauungsstörungen,0.333,1.395,0.073,-0.031,0.697
5,Infertilitaet,1.050,2.858,0.000,0.674,1.426
6,Rückenschmerzen,0.389,1.475,0.002,0.143,0.634
7,Verstopfung,-0.106,0.900,0.840,-1.134,0.922
8,Bauch_und_Beckenschmerzen,0.750,2.118,0.000,0.617,0.884
9,Blutung,0.459,1.582,0.000,0.231,0.687
10,Durchfall,-19.250,0.000,0.999,-23867.619,23829.119
11,Urinieren,0.774,2.168,0.000,0.423,1.124
12,NSAR,0.259,1.296,0.000,0.117,0.402
13,Dyspareunie,0.285,1.330,0.701,-1.172,1.741
14,Orale_Kontrazeptiva,-0.299,0.741,0.001,-0.473,-0.126

In [43]:
menstruationsschmerz_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.038       0.018      0.0    -4.102    -3.975
1  Menstruationsschmerzen  1.033       2.809      0.0     0.911     1.155

In [46]:
basis_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature    coef  odds_ratio  p_value   ci_lower   ci_upper
0               Intercept  -4.182       0.015    0.000     -4.251     -4.114
1             Verstopfung  -0.085       0.919    0.870     -1.099      0.929
2  Menstruationsschmerzen   0.809       2.246    0.000      0.681      0.938
3     Verdauungsstörungen   0.377       1.458    0.041      0.015      0.740
4             Dyspareunie   0.361       1.435    0.625     -1.087      1.809
5               Urinieren   0.812       2.253    0.000      0.464      1.161
6                 Blutung   0.477       1.611    0.000      0.250      0.703
7          Bauchschmerzen   0.819       2.268    0.000      0.689      0.949
8               Durchfall -18.616       0.000    0.999 -24912.987  24875.754

In [40]:
urinieren_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.177       0.015    0.000    -4.246    -4.109
1             Verstopfung -0.058       0.944    0.911    -1.067     0.951
2  Menstruationsschmerzen  0.817       2.265    0.000     0.689     0.946
3     Verdauungsstörungen  0.378       1.459    0.041     0.016     0.740
4             Dyspareunie  0.362       1.436    0.624    -1.087     1.811
5                 Blutung  0.489       1.630    0.000     0.263     0.715
6          Bauchschmerzen  0.845       2.329    0.000     0.716     0.975

In [39]:
dyspareunie_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.182       0.015    0.000    -4.251    -4.113
1             Verstopfung -0.113       0.893    0.828    -1.126     0.901
2  Menstruationsschmerzen  0.810       2.248    0.000     0.682     0.938
3     Verdauungsstörungen  0.380       1.462    0.040     0.018     0.742
4               Urinieren  0.813       2.255    0.000     0.465     1.161
5                 Blutung  0.476       1.609    0.000     0.249     0.702
6          Bauchschmerzen  0.819       2.268    0.000     0.689     0.949

In [33]:
durchfall_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.182       0.015    0.000    -4.251    -4.114
1             Verstopfung -0.112       0.894    0.829    -1.125     0.902
2  Menstruationsschmerzen  0.809       2.246    0.000     0.681     0.937
3     Verdauungsstörungen  0.378       1.460    0.041     0.016     0.741
4             Dyspareunie  0.361       1.435    0.625    -1.087     1.809
5               Urinieren  0.813       2.255    0.000     0.465     1.161
6                 Blutung  0.476       1.610    0.000     0.249     0.703
7          Bauchschmerzen  0.818       2.267    0.000     0.688     0.949