# Fit DAG

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
    
import sys
sys.path.append("..")
sys.path.append("../prediction_src")

import pandas as pd

import numpy as np


from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm

import random
import pickle
import sklearn

from sklearn.metrics import roc_auc_score, brier_score_loss
from collections import defaultdict


from sklearn.model_selection import KFold, cross_validate 

from evaluate_prediction_model import *

from sklearn.base import BaseEstimator, ClassifierMixin
import statsmodels.api as sm

from prediction_src.fit_prediction_model import *

from prediction_src.prediction_pipeline import model_pipeline

In [3]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:
is_sum = False
as_grouped = True
nvf=False

In [5]:
from params import *

In [6]:
filepath = "../data/processed/n80_df.pkl"

In [7]:
NO_DURCHFALL_COLS = GROUP_COLS.copy()
NO_DURCHFALL_MODEL_COLS = GROUP_MODEL_COLS.copy()

NO_DURCHFALL_COLS.pop(NO_DURCHFALL_COLS.index("Durchfall"))

NO_DURCHFALL_MODEL_COLS.pop(NO_DURCHFALL_MODEL_COLS.index("Durchfall"))

'Durchfall'

In [8]:
NO_DURCHFALL_DYSPAREUNIE_COLS = NO_DURCHFALL_COLS.copy()
NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS = NO_DURCHFALL_MODEL_COLS.copy()
NO_DURCHFALL_DYSPAREUNIE_COLS.pop(NO_DURCHFALL_DYSPAREUNIE_COLS.index("Dyspareunie"))

NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS.pop(NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS.index("Dyspareunie"))

'Dyspareunie'

In [9]:
NO_DURCHFALL_DYSPAREUNIE_COLS

['Verstopfung',
 'Blutung',
 'Menstruationsschmerzen',
 'Bauchschmerzen',
 'Verdauungsstörungen',
 'Urinieren']

In [10]:
NO_DURCHFALL_DYSCHEZIE_COLS = NO_DURCHFALL_COLS.copy()
NO_DURCHFALL_DYSCHEZIE_MODEL_COLS = NO_DURCHFALL_MODEL_COLS.copy()

NO_DURCHFALL_DYSCHEZIE_COLS.pop(NO_DURCHFALL_DYSCHEZIE_COLS.index("Urinieren"))

NO_DURCHFALL_DYSCHEZIE_MODEL_COLS.pop(NO_DURCHFALL_DYSCHEZIE_MODEL_COLS.index("Urinieren"))

'Urinieren'

In [11]:
NO_DURCHFALL_DYSCHEZIE_COLS

['Dyspareunie',
 'Verstopfung',
 'Blutung',
 'Menstruationsschmerzen',
 'Bauchschmerzen',
 'Verdauungsstörungen']

In [12]:
MENS_DATA_COLS = NO_DURCHFALL_COLS.copy()
MENS_DATA_COLS.pop(MENS_DATA_COLS.index("Menstruationsschmerzen"))

'Menstruationsschmerzen'

In [14]:
mensdata = pd.read_pickle("../data/processed/menstruationsschmerz_data.pkl")

In [15]:
mensdata["endo"].value_counts()

endo
False    11667
True       596
Name: count, dtype: int64

In [25]:
grouped_models = dict()
mens_data_dict = train_model(mensdata, TARGET_COLUMN,as_grouped, is_sum,nvf,MENS_DATA_COLS,SPLIT_SIZE,
                grouped_models,THRESHOLD,N_FOLDS,SCORER)

In [24]:
model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,GROUP_COLS,GROUP_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

In [26]:
menstruationsschmerz_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,MENS_COLS,MENS_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

In [27]:
durchfall_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_COLS,NO_DURCHFALL_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

creating target_column
(99870,)

In [ ]:
urinieren_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_DYSCHEZIE_COLS,NO_DURCHFALL_DYSCHEZIE_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

In [ ]:
dyspareunie_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,CODE_TO_LABEL,NO_DURCHFALL_DYSPAREUNIE_COLS,NO_DURCHFALL_DYSPAREUNIE_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

In [ ]:
nvf_model_dict = model_pipeline(filepath,TARGET_COLUMN,as_grouped,nvf,NVF_CODE_TO_LABEL,NVF_GROUP_COLS,NVF_MODEL_COLS,is_sum,SPLIT_SIZE,
                THRESHOLD,N_FOLDS,SCORER)

In [76]:
with open("../models/DAG_model_thresh_new.pkl","wb") as f:
    pickle.dump(model_dict,f)

In [77]:
with open("../models/menstruationsschmerz_predictor.pkl","wb") as f:
    pickle.dump(menstruationsschmerz_dict,f)

In [78]:
with open("../models/mens_data_model.pkl","wb") as f:
    pickle.dump(mens_data_dict,f)

In [79]:
with open("../models/DAG_model_durchfall.pkl","wb") as f:
    pickle.dump(durchfall_model_dict,f)

In [83]:
with open("../models/DAG_model_dyspareunie.pkl","wb") as f:
    pickle.dump(dyspareunie_model_dict,f)

In [81]:
with open("../models/DAG_model_urinieren.pkl","wb") as f:
    pickle.dump(urinieren_model_dict,f)

In [82]:
with open("../models/DAG_model_nvf.pkl","wb") as f:
    pickle.dump(nvf_model_dict,f)

## Load models

In [21]:
with open("../models/DAG_model_durchfall.pkl","rb") as f:
    durchfall_model_dict = pickle.load(f)

In [22]:
with open("../models/DAG_model_dyspareunie.pkl","rb") as f:
    dyspareunie_model_dict = pickle.load(f)

In [22]:
with open("../models/DAG_model_urinieren.pkl","rb") as f:
    urinieren_model_dict = pickle.load(f)

In [23]:
nvf_model = nvf_model_dict[list(nvf_model_dict.keys())[0]]["model"]

In [28]:
mens_data_model = mens_data_dict[list(mens_data_dict.keys())[0]]["model"]

In [29]:
menstruationsschmerz_model = menstruationsschmerz_dict[list(menstruationsschmerz_dict.keys())[0]]["model"]

In [30]:
durchfall_dag_model = durchfall_model_dict[list(durchfall_model_dict.keys())[0]]["model"]

In [71]:
dyspareunie_dag_model = dyspareunie_model_dict[list(dyspareunie_model_dict.keys())[0]]["model"]

In [72]:
urinieren_dag_model = urinieren_model_dict[list(urinieren_model_dict.keys())[0]]["model"]

In [38]:
nvf_model.coef_table_.round(3) # endometriosis without adenomyosis

,feature,coef,odds_ratio,p_value,ci_lower,ci_upper
0,Intercept,-4.213,0.015,0.000,-4.287,-4.139
1,Menstruationsschmerzen,0.838,2.312,0.000,0.707,0.969
2,Bauchschmerzen,0.583,1.791,0.010,0.137,1.029
3,Kopfschmerzen,0.741,2.098,0.009,0.184,1.298
4,Verdauungsstörungen,0.333,1.395,0.073,-0.031,0.697
5,Infertilitaet,1.050,2.858,0.000,0.674,1.426
6,Rückenschmerzen,0.389,1.475,0.002,0.143,0.634
7,Verstopfung,-0.106,0.900,0.840,-1.134,0.922
8,Bauch_und_Beckenschmerzen,0.750,2.118,0.000,0.617,0.884
9,Blutung,0.459,1.582,0.000,0.231,0.687
10,Durchfall,-19.250,0.000,0.999,-23867.619,23829.119
11,Urinieren,0.774,2.168,0.000,0.423,1.124
12,NSAR,0.259,1.296,0.000,0.117,0.402
13,Dyspareunie,0.285,1.330,0.701,-1.172,1.741
14,Orale_Kontrazeptiva,-0.299,0.741,0.001,-0.473,-0.126

In [84]:
menstruationsschmerz_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.038       0.018      0.0    -4.102    -3.975
1  Menstruationsschmerzen  1.033       2.809      0.0     0.911     1.155

In [42]:
mens_data_model.coef_table_.round(3) # endometriosis without adenomyosis

               feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0            Intercept -3.212       0.040    0.000    -3.348    -3.077
1          Dyspareunie  0.245       1.278    0.814    -1.795     2.286
2          Verstopfung  0.836       2.306    0.277    -0.670     2.341
3              Blutung  0.461       1.585    0.002     0.168     0.753
4       Bauchschmerzen  0.582       1.789    0.000     0.365     0.798
5  Verdauungsstörungen -0.103       0.902    0.757    -0.757     0.550
6            Urinieren  0.315       1.370    0.290    -0.269     0.898

In [73]:
urinieren_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.177       0.015    0.000    -4.246    -4.109
1  Menstruationsschmerzen  0.817       2.265    0.000     0.689     0.946
2          Bauchschmerzen  0.845       2.329    0.000     0.716     0.975
3     Verdauungsstörungen  0.378       1.459    0.041     0.016     0.740
4             Verstopfung -0.058       0.944    0.911    -1.067     0.951
5                 Blutung  0.489       1.630    0.000     0.263     0.715
6             Dyspareunie  0.362       1.436    0.624    -1.087     1.811

In [74]:
dyspareunie_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.182       0.015    0.000    -4.251    -4.113
1  Menstruationsschmerzen  0.810       2.248    0.000     0.682     0.938
2          Bauchschmerzen  0.819       2.268    0.000     0.689     0.949
3     Verdauungsstörungen  0.380       1.462    0.040     0.018     0.742
4             Verstopfung -0.113       0.893    0.828    -1.126     0.901
5                 Blutung  0.476       1.609    0.000     0.249     0.702
6               Urinieren  0.813       2.255    0.000     0.465     1.161

In [46]:
durchfall_dag_model.coef_table_.round(3) # endometriosis without adenomyosis

                  feature   coef  odds_ratio  p_value  ci_lower  ci_upper
0               Intercept -4.182       0.015    0.000    -4.251    -4.114
1  Menstruationsschmerzen  0.809       2.246    0.000     0.681     0.937
2          Bauchschmerzen  0.818       2.267    0.000     0.688     0.949
3     Verdauungsstörungen  0.378       1.460    0.041     0.016     0.741
4             Verstopfung -0.112       0.894    0.829    -1.125     0.902
5                 Blutung  0.476       1.610    0.000     0.249     0.703
6               Urinieren  0.813       2.255    0.000     0.465     1.161
7             Dyspareunie  0.361       1.435    0.625    -1.087     1.809

In [49]:
model_dict[list(model_dict.keys())[0]]["model"].coef_table_.round(3) # endometriosis without adenomyosis

                  feature    coef  odds_ratio  p_value   ci_lower   ci_upper
0               Intercept  -4.182       0.015    0.000     -4.251     -4.114
1  Menstruationsschmerzen   0.809       2.246    0.000      0.681      0.938
2          Bauchschmerzen   0.819       2.268    0.000      0.689      0.949
3     Verdauungsstörungen   0.377       1.458    0.041      0.015      0.740
4             Verstopfung  -0.085       0.919    0.870     -1.099      0.929
5                 Blutung   0.477       1.611    0.000      0.250      0.703
6               Durchfall -18.616       0.000    0.999 -24912.987  24875.754
7               Urinieren   0.812       2.253    0.000      0.464      1.161
8             Dyspareunie   0.361       1.435    0.625     -1.087      1.809